[package]
name = "rust_astro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at 
# https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name="astro"
crate-type = ["cdylib"]


[dependencies]
nalgebra = "0.31.0"
nix = "0.24.1"
lazy_static = "1.4.0"
chrono = "0.4.19"
ode_solvers = "0.3.7"
reqwest =  {version="0.11.11", features = ["blocking"]}
numpy = {version="0.17.2", optional=true}
# nalgebra-numpy = {version="0.3.0", optional=true}
pyo3 = {version="0.17.2", features=["extension-module"], optional=true}
cty = "0.2.2"

[build-dependencies]
cc = {version="1.0.74", features=["parallel"]}

[dev-dependencies]

[features]
default = ["pybindings"]
pybindings = [
    "pyo3",
    "numpy",
]
