[package]
name = "rust_astro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.0"
nix = "0.24.1"
lazy_static = "1.4.0"