[package]
name = "astro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at 
# https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name="astro"
crate-type = ["dylib"]


[dependencies]
nalgebra = "0.32.3"
libc = "0.2.150"
lazy_static = "1.4.0"
chrono = "0.4.31"
ode_solvers = "0.3.7"
reqwest =  {version="0.11.11", features = ["blocking"]}
numpy = {version="0.20.0", optional=true}
# nalgebra-numpy = {version="0.3.0", optional=true}
pyo3 = {version="0.20.0", features=[], optional=true}
cty = "0.2.2"

[build-dependencies]
cc = {version="1.0.83", features=["parallel"]}
chrono = "0.4.31"
pyo3-build-config = { version = "0.20.0", optional = true}

[dev-dependencies]

[features]
default = ["pybindings"]
pybindings = [
    "pyo3",
    "numpy",
    "pyo3-build-config" 
]
