name: Build

on:
  push:
    branches:
      - satkit

jobs:
  build:
    name: build and test satkit
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu

    runs-on: ${{ format('{0}-latest', matrix.os) }}

    env:
      ASTRO_DATA: astro-data
      SATKIT_TESTVEC_ROOT: satkit-testvecs

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      # Download the data and the test vectors
      - run: python pytest/download_data.py
      - run: python pytest/download_testvecs.py

      - uses: actions-rs/cargo@v1
        with:
          command: test
