name: Build

on:
  push:
    branches:
      - satkit

jobs:
  build:
    name: build on ${{ matrix.platform || matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos
          - ubuntu
          - windows
        include:
          - os: ubuntu
            platform: linux
          - os: windows
            ls: dir

    runs-on: ${{ format('{0}-latest', matrix.os) }}
    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5

      - name: set up rust
        if: matrix.os != 'ubuntu'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: install python dependencies
        run: pip install -U setuptools wheel cibuildwheel

      # Details of cibuildwheel are set in pyproject.toml
      - name: build ${{ matrix.platform || matrix.os }} binaries
        run: cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
